### ISSUE TITLE
 work on 127.0.0.1/0.0.0.0  but not on 192.168.11.105

### ISSUE THREAD

**Issue by mn3711698** [channelcat/sanic#930]
search issues not find.

@app.route('/' , methods=['GET', 'POST'])
@app.route('/houtai' , methods=['GET', 'POST'])
def houtai(request):
    print('in-----in====')
    try:
        objHandle=request
        if objHandle.method == 'POST':
            REQUEST = objHandle.form
        else:
            REQUEST = objHandle.args
        print('---====')
        viewid = REQUEST.get('viewid','')
        print('入口＝＝＝＝＝＝')
        session_cookie = objHandle.cookies.get("%s__session"%CLIENT_NAME)
        print(viewid,session_cookie,'iiiiiiiiiii---')
on pycharm run.

if __name__ == '__main__':
    app.run(host='0.0.0.0',port=5002)
0.0.0.0:5002   is ok

if __name__ == '__main__':
    app.run(port=5002)
127.0.0.1:5002  is ok

if __name__ == '__main__':
    app.run(host='192.168.11.105',port=5002)
192.168.11.105:5002   can't

2017-09-03 09:06:10 - (sanic)[INFO]: Goin' Fast @ http://192.168.11.105:5002
2017-09-03 09:06:10 - (sanic)[INFO]: Starting worker [5104]
in-----in====
---====
入口＝＝＝＝＝＝
2017-09-03 09:06:13 - (sanic)[ERROR]: Invalid response object for url b'/', Expected Type: HTTPResponse, Actual Type: <class 'str'>
2017-09-03 09:06:13 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 246, in write_response
    response.output(
AttributeError: 'str' object has no attribute 'output'

2017-09-03 09:06:13 - (network)[INFO][UNKNOWN]: nil  500 28

sanic is 0.6.0

root@xxx-MS-7529:/home/xxx# uname -a
Linux xxx-MS-7529 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux

but :
@app.route('/ , methods=['GET', 'POST'])
def test(request):
    return response.text('hello')

is ok!

**Comment by mn3711698** [comment]
i reboot pc will ok.

**Comment by HsGaurav** [comment]
> reboot

what does this mean?

**Comment by HsGaurav** [comment]
> search issues not find.
> 
> @app.route('/' , methods=['GET', 'POST'])
> @app.route('/houtai' , methods=['GET', 'POST'])
> def houtai(request):
> print('in-----in====')
> try:
> objHandle=request
> if objHandle.method == 'POST':
> REQUEST = objHandle.form
> else:
> REQUEST = objHandle.args
> print('---====')
> viewid = REQUEST.get('viewid','')
> print('入口＝＝＝＝＝＝')
> session_cookie = objHandle.cookies.get("%s__session"%CLIENT_NAME)
> print(viewid,session_cookie,'iiiiiiiiiii---')
> on pycharm run.
> 
> if **name** == '**main**':
> app.run(host='0.0.0.0',port=5002)
> 0.0.0.0:5002 is ok
> 
> if **name** == '**main**':
> app.run(port=5002)
> 127.0.0.1:5002 is ok
> 
> if **name** == '**main**':
> app.run(host='192.168.11.105',port=5002)
> 192.168.11.105:5002 can't
> 
> 2017-09-03 09:06:10 - (sanic)[INFO]: Goin' Fast @ http://192.168.11.105:5002
> 2017-09-03 09:06:10 - (sanic)[INFO]: Starting worker [5104]
> in-----in====
> ---====
> 入口＝＝＝＝＝＝
> 2017-09-03 09:06:13 - (sanic)[ERROR]: Invalid response object for url b'/', Expected Type: HTTPResponse, Actual Type: <class 'str'>
> 2017-09-03 09:06:13 - (sanic)[ERROR]: Traceback (most recent call last):
> File "/usr/local/lib/python3.5/dist-packages/sanic/server.py", line 246, in write_response
> response.output(
> AttributeError: 'str' object has no attribute 'output'
> 
> 2017-09-03 09:06:13 - (network)[INFO][UNKNOWN]: nil 500 28
> 
> sanic is 0.6.0
> 
> root@xxx-MS-7529:/home/xxx# uname -a
> Linux xxx-MS-7529 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
> 
> but :
> @app.route('/ , methods=['GET', 'POST'])
> def test(request):
> return response.text('hello')
> 
> is ok!

gitting same error but instead of str I'm getting NoneType in a delete request

**Comment by ahopkins** [comment]
@HsGaurav If you are experiencing an issue, can you please open a new discussion. If it is a support issue, it is best on https://community.sanicframework.org/

**Comment by codenoid** [comment]
you reboot the PC ?
